#!/usr/bin/env python3
"""
generate_spatial_footprints.py

Generate synthetic spatial footprints for the Stars2Cells benchmark datasets.
Adds a `spatial_mapping/` subfolder to each benchmark directory containing
per-session footprint arrays in CellReg-compatible format (N × H × W).

Design philosophy:
  - Footprints are generated ONCE per neuron per animal (from base coordinates).
  - The same footprint *shape* (eccentricity, orientation, peak intensity) is
    reused across every seed, condition, and session for that animal.
  - Per-session spatial transforms (rotation, translation, jitter, dropout)
    are applied to position each footprint correctly, matching the centroids
    already generated by generate_benchmark_data.py.
  - This gives CellReg the BEST POSSIBLE scenario for spatial correlation:
    distinctive, consistent footprints that never change shape — only position.

Footprint sizing rationale:
  Mouse pyramidal neuron somata average ~20 µm in diameter (Bear et al.,
  "Neuroscience: Exploring the Brain"; Wikipedia "Pyramidal cell"). In
  one-photon miniscope imaging, the effective spatial footprint extracted
  by CNMF/CNMF-E is typically larger than the soma due to neuropil
  contamination and optical scattering, yielding effective radii of ~8–15 µm
  (Pnevmatikakis et al. 2016; Zhou et al. 2018). CNMF-E models neuron shapes
  as roughly spherical with a user-specified diameter (Inscopix CNMF-E docs).

  For the benchmark (FOV = 600 × 600 px, µm/px = 1.0), we scale the mean
  footprint radius by neuron count to reflect realistic packing density:

    n_neurons | mean_radius_px | biological justification
    ----------|----------------|------------------------------------------
        100   |   12.0         | sparse field, full soma + neuropil halo
        250   |   10.0         | moderate density, slight halo compression
        500   |    8.0         | dense field, CNMF shrinks to reduce overlap
       1000   |    6.0         | very dense, footprints approach soma-only

  Per-neuron variation in semi-axes (±30%), orientation (0–180°), and peak
  intensity (0.6–1.0) ensures each footprint is distinctive for spatial
  correlation matching.

Output format (per session file):
  spatial_footprints.npy  →  dict with key = session filename, value = dict:
    'footprints': np.ndarray [N × H × W]  float32, CellReg-compatible
    'centroids_x': np.ndarray [N]
    'centroids_y': np.ndarray [N]
    'roi_ids': np.ndarray [N]

  Also saves a per-animal base footprint template:
    {animal_id}_base_footprints.npy → dict with footprint shape params

Usage:
    python generate_spatial_footprints.py
"""

import numpy as np
from pathlib import Path
from dataclasses import dataclass
from typing import Optional


# ═══════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class FootprintConfig:
    """Configuration for spatial footprint generation."""
    fov_size: int = 600                # pixels (matches benchmark FOV)
    microns_per_pixel: float = 1.0     # benchmark uses 1:1

    # Mean footprint radius (pixels) by neuron count tier.
    # Based on: mouse pyramidal soma ~20 µm diameter (Bear et al.),
    # CNMF-E effective footprint ~8-15 µm radius depending on density
    # (Pnevmatikakis et al. 2016, Zhou et al. 2018).
    # Scaled for 600×600 FOV — ~1.37× more area than 512², so neurons
    # are sparser at equivalent counts, allowing slightly larger footprints.
    radius_by_n: dict = None

    # Per-neuron shape variation
    eccentricity_range: tuple = (0.6, 1.0)   # ratio of semi-minor to semi-major
    orientation_jitter: bool = True           # random orientation per neuron
    intensity_range: tuple = (0.6, 1.0)       # peak intensity variation
    radius_cv: float = 0.15                   # coefficient of variation for radius

    # Footprint rendering
    footprint_crop_radius_factor: float = 2.5  # render out to 2.5× sigma
    normalize_footprints: bool = True          # L2-normalize each footprint

    # Storage mode: 'dense' saves full N×H×W arrays (CellReg-compatible),
    # 'compact' saves per-neuron cropped patches + offsets (much smaller).
    # Note: dense 1000-neuron sessions are ~1.4 GB each at 600×600. With
    # 1600 sessions across the full benchmark that's ~2.2 TB. Use 'compact'
    # to store efficiently and reconstruct dense arrays on-the-fly for CellReg.
    storage_mode: str = 'both'  # 'dense', 'compact', or 'both'

    def __post_init__(self):
        if self.radius_by_n is None:
            # Empirical scaling: sparser fields → larger effective footprints
            # because CNMF has less need to shrink components to resolve overlap.
            # Radii bumped ~1 px vs 512² values to reflect lower packing density
            # in the larger 600×600 FOV (~1.37× more area at same neuron count).
            self.radius_by_n = {
                100:  12.0,   # ~24 µm diameter — full soma + neuropil halo
                250:  10.0,   # ~20 µm — moderate compression
                500:   8.0,   # ~16 µm — dense field, approaching soma size
                1000:  6.0,   # ~12 µm — very dense, near soma-only
            }

    def get_mean_radius(self, n_neurons: int) -> float:
        """Interpolate mean radius for arbitrary neuron count."""
        tiers = sorted(self.radius_by_n.keys())
        if n_neurons <= tiers[0]:
            return self.radius_by_n[tiers[0]]
        if n_neurons >= tiers[-1]:
            return self.radius_by_n[tiers[-1]]
        # Linear interpolation between tiers
        for i in range(len(tiers) - 1):
            if tiers[i] <= n_neurons <= tiers[i + 1]:
                frac = (n_neurons - tiers[i]) / (tiers[i + 1] - tiers[i])
                r_lo = self.radius_by_n[tiers[i]]
                r_hi = self.radius_by_n[tiers[i + 1]]
                return r_lo + frac * (r_hi - r_lo)
        return self.radius_by_n[tiers[-1]]


# ═══════════════════════════════════════════════════════════════════════════
# Core: generate base footprint templates for one animal
# ═══════════════════════════════════════════════════════════════════════════

def generate_base_footprint_params(n_neurons, animal_seed, config: FootprintConfig):
    """
    Generate per-neuron footprint shape parameters for one animal.
    These are FIXED across all sessions, seeds, and conditions.

    Returns
    -------
    params : dict with keys:
        'sigma_major':   [N] semi-major axis (pixels)
        'sigma_minor':   [N] semi-minor axis (pixels)
        'orientation':   [N] rotation angle (radians)
        'peak_intensity':[N] relative peak brightness
    """
    rng = np.random.RandomState(animal_seed + 99999)  # dedicated seed

    mean_radius = config.get_mean_radius(n_neurons)

    # Per-neuron radius with CV variation
    sigma_major = rng.normal(mean_radius, mean_radius * config.radius_cv, n_neurons)
    sigma_major = np.clip(sigma_major, mean_radius * 0.5, mean_radius * 1.8)

    # Eccentricity: ratio of minor/major axis
    ecc = rng.uniform(*config.eccentricity_range, n_neurons)
    sigma_minor = sigma_major * ecc

    # Orientation: uniform 0–π (only matters if eccentric)
    if config.orientation_jitter:
        orientation = rng.uniform(0, np.pi, n_neurons)
    else:
        orientation = np.zeros(n_neurons)

    # Peak intensity variation
    peak_intensity = rng.uniform(*config.intensity_range, n_neurons)

    return {
        'sigma_major': sigma_major.astype(np.float32),
        'sigma_minor': sigma_minor.astype(np.float32),
        'orientation': orientation.astype(np.float32),
        'peak_intensity': peak_intensity.astype(np.float32),
        'mean_radius': mean_radius,
        'n_neurons': n_neurons,
    }


# ═══════════════════════════════════════════════════════════════════════════
# Render a single 2D elliptical Gaussian footprint into a FOV
# ═══════════════════════════════════════════════════════════════════════════

def render_footprint(cx, cy, sigma_major, sigma_minor, orientation, peak,
                     fov_size, crop_factor=2.5):
    """
    Render one elliptical Gaussian footprint into a (fov_size × fov_size) image.

    Parameters
    ----------
    cx, cy          : float, centroid position (pixels)
    sigma_major/minor: float, semi-axes (pixels)
    orientation     : float, rotation angle (radians)
    peak            : float, peak intensity
    fov_size        : int
    crop_factor     : float, render within crop_factor * max_sigma

    Returns
    -------
    footprint : np.ndarray [fov_size × fov_size], float32 (sparse-friendly)
    """
    max_sigma = max(sigma_major, sigma_minor)
    crop_r = int(np.ceil(crop_factor * max_sigma))

    # Bounding box (clipped to FOV)
    y_lo = max(0, int(cy) - crop_r)
    y_hi = min(fov_size, int(cy) + crop_r + 1)
    x_lo = max(0, int(cx) - crop_r)
    x_hi = min(fov_size, int(cx) + crop_r + 1)

    if y_hi <= y_lo or x_hi <= x_lo:
        return np.zeros((fov_size, fov_size), dtype=np.float32)

    # Local grid relative to centroid
    yy, xx = np.mgrid[y_lo:y_hi, x_lo:x_hi]
    dx = xx - cx
    dy = yy - cy

    # Rotate to footprint's principal axes
    cos_t = np.cos(orientation)
    sin_t = np.sin(orientation)
    dx_rot = dx * cos_t + dy * sin_t
    dy_rot = -dx * sin_t + dy * cos_t

    # Elliptical Gaussian
    exponent = -0.5 * ((dx_rot / sigma_major) ** 2 + (dy_rot / sigma_minor) ** 2)
    patch = peak * np.exp(exponent)

    # Place into full FOV
    footprint = np.zeros((fov_size, fov_size), dtype=np.float32)
    footprint[y_lo:y_hi, x_lo:x_hi] = patch.astype(np.float32)

    return footprint


def render_footprint_compact(cx, cy, sigma_major, sigma_minor, orientation, peak,
                             fov_size, crop_factor=2.5):
    """
    Render one footprint and return ONLY the cropped patch + bounding box.
    Much more memory-efficient than full FOV arrays.

    Returns
    -------
    patch : np.ndarray [h × w], float32
    bbox  : tuple (y_lo, y_hi, x_lo, x_hi)
    """
    max_sigma = max(sigma_major, sigma_minor)
    crop_r = int(np.ceil(crop_factor * max_sigma))

    y_lo = max(0, int(cy) - crop_r)
    y_hi = min(fov_size, int(cy) + crop_r + 1)
    x_lo = max(0, int(cx) - crop_r)
    x_hi = min(fov_size, int(cx) + crop_r + 1)

    if y_hi <= y_lo or x_hi <= x_lo:
        return np.zeros((1, 1), dtype=np.float32), (0, 1, 0, 1)

    yy, xx = np.mgrid[y_lo:y_hi, x_lo:x_hi]
    dx = xx - cx
    dy = yy - cy
    cos_t = np.cos(orientation)
    sin_t = np.sin(orientation)
    dx_rot = dx * cos_t + dy * sin_t
    dy_rot = -dx * sin_t + dy * cos_t
    exponent = -0.5 * ((dx_rot / sigma_major) ** 2 + (dy_rot / sigma_minor) ** 2)
    patch = (peak * np.exp(exponent)).astype(np.float32)

    return patch, (y_lo, y_hi, x_lo, x_hi)


def reconstruct_dense_from_compact(compact_data, fov_size=None):
    """
    Reconstruct a full CellReg-compatible N×H×W array from compact storage.

    Parameters
    ----------
    compact_data : dict with 'patches' (list of arrays), 'bboxes' (list of tuples),
                   and optionally 'fov_size' (int)
    fov_size     : int, override; if None, reads from compact_data['fov_size'] (default 600)

    Returns
    -------
    footprints : np.ndarray [N × fov × fov], float32
    """
    if fov_size is None:
        fov_size = compact_data.get('fov_size', 600)
    patches = compact_data['patches']
    bboxes = compact_data['bboxes']
    n = len(patches)
    footprints = np.zeros((n, fov_size, fov_size), dtype=np.float32)
    for i in range(n):
        y_lo, y_hi, x_lo, x_hi = bboxes[i]
        footprints[i, y_lo:y_hi, x_lo:x_hi] = patches[i]
    return footprints


# ═══════════════════════════════════════════════════════════════════════════
# Build full footprint array for one session
# ═══════════════════════════════════════════════════════════════════════════

def build_session_footprints(session_data, base_params, config: FootprintConfig):
    """
    Build footprints for one session in dense and/or compact format.

    Parameters
    ----------
    session_data : dict loaded from .npy session file
    base_params  : dict from generate_base_footprint_params
    config       : FootprintConfig

    Returns
    -------
    result : dict with keys depending on config.storage_mode:
        'dense':   np.ndarray [N × H × W] float32 (CellReg-compatible)
        'compact': dict with 'patches' (list[ndarray]) and 'bboxes' (list[tuple])
    """
    cx = np.array(session_data['centroids_x'], dtype=float)
    cy = np.array(session_data['centroids_y'], dtype=float)
    roi_ids = np.array(session_data['roi_ids'], dtype=int)
    n_cells = len(cx)
    fov = config.fov_size
    want_dense = config.storage_mode in ('dense', 'both')
    want_compact = config.storage_mode in ('compact', 'both')

    dense_arr = np.zeros((n_cells, fov, fov), dtype=np.float32) if want_dense else None
    patches = [] if want_compact else None
    bboxes = [] if want_compact else None

    for i in range(n_cells):
        base_id = roi_ids[i]
        # Turnover neurons (base_id > n_base) get shapes via modular indexing
        idx = base_id % base_params['n_neurons']

        sm = base_params['sigma_major'][idx]
        sn = base_params['sigma_minor'][idx]
        ori = base_params['orientation'][idx]
        pk = base_params['peak_intensity'][idx]

        # Always render compact (small patch) — reconstruct dense from it
        patch, bbox = render_footprint_compact(
            cx[i], cy[i], sm, sn, ori, pk, fov,
            config.footprint_crop_radius_factor)

        if config.normalize_footprints:
            norm = np.sqrt((patch ** 2).sum())
            if norm > 0:
                patch = patch / norm

        if want_compact:
            patches.append(patch)
            bboxes.append(bbox)

        if want_dense:
            y_lo, y_hi, x_lo, x_hi = bbox
            dense_arr[i, y_lo:y_hi, x_lo:x_hi] = patch

    result = {}
    if want_dense:
        result['dense'] = dense_arr
    if want_compact:
        result['compact'] = {'patches': patches, 'bboxes': bboxes}
    return result


# ═══════════════════════════════════════════════════════════════════════════
# Main: iterate over benchmark directories
# ═══════════════════════════════════════════════════════════════════════════

def generate_all_footprints(
    benchmark_dirs: list,
    n_neurons_list: list,
    n_animals: int = 8,
    config: Optional[FootprintConfig] = None,
    verbose: bool = True,
):
    """
    Generate spatial_mapping/ subfolders for each benchmark directory.

    Parameters
    ----------
    benchmark_dirs  : list of str/Path, one per neuron count
    n_neurons_list  : list of int, matching benchmark_dirs
    n_animals       : int
    config          : FootprintConfig (uses defaults if None)
    """
    if config is None:
        config = FootprintConfig()

    for bench_dir, n_neurons in zip(benchmark_dirs, n_neurons_list):
        bench_dir = Path(bench_dir)
        if not bench_dir.exists():
            print(f"SKIP (not found): {bench_dir}")
            continue

        out_dir = bench_dir / "spatial_mapping"

        # ── Skip if already generated ──
        existing = list(out_dir.glob("*_footprints_compact.npy")) if out_dir.exists() else []
        session_files = sorted(bench_dir.glob("*__seed*.npy"))
        if len(existing) >= len(session_files) and len(existing) > 0:
            if verbose:
                print(f"\n  SKIP {bench_dir.name}: spatial_mapping/ already has "
                      f"{len(existing)} files (>= {len(session_files)} sessions)")
            continue

        out_dir.mkdir(exist_ok=True)

        if verbose:
            mean_r = config.get_mean_radius(n_neurons)
            print(f"\n{'═' * 60}")
            print(f"  {bench_dir.name}")
            print(f"  n_neurons={n_neurons}  mean_radius={mean_r:.1f} px "
                  f"(~{mean_r * 2 * config.microns_per_pixel:.0f} µm diameter)")
            print(f"{'═' * 60}")

        # ── Generate base footprint params per animal ──
        base_params_by_animal = {}
        for animal_idx in range(n_animals):
            animal_id = str(n_neurons + animal_idx + 1)
            animal_seed = animal_idx * 10_000
            params = generate_base_footprint_params(n_neurons, animal_seed, config)
            base_params_by_animal[animal_id] = params

            # Save base params for reference
            np.save(out_dir / f"{animal_id}_base_footprint_params.npy",
                    params, allow_pickle=True)

        # ── Process every session .npy file ──
        if not session_files:
            session_files = sorted(bench_dir.glob("*__seed*.npy"))
        file_count = 0
        skip_count = 0

        for sf in session_files:
            # Extract animal ID from filename: {animal}_{sess}__{condition}__seed{seed}.npy
            parts = sf.stem.split('_')
            animal_id = parts[0]

            if animal_id not in base_params_by_animal:
                continue

            # Skip if this session's footprints already exist
            out_base = sf.stem + "_footprints"
            compact_exists = (out_dir / (out_base + "_compact.npy")).exists()
            dense_exists   = (out_dir / (out_base + ".npy")).exists()
            want_compact = config.storage_mode in ('compact', 'both')
            want_dense   = config.storage_mode in ('dense', 'both')
            if (want_compact and compact_exists) or (want_dense and dense_exists):
                skip_count += 1
                continue

            session_data = np.load(sf, allow_pickle=True).item()
            base_params = base_params_by_animal[animal_id]

            result = build_session_footprints(session_data, base_params, config)

            # Save compact version (always small — ~1-5 MB per session)
            if 'compact' in result:
                compact_data = {
                    'patches': result['compact']['patches'],
                    'bboxes': result['compact']['bboxes'],
                    'centroids_x': session_data['centroids_x'],
                    'centroids_y': session_data['centroids_y'],
                    'roi_ids': session_data['roi_ids'],
                    'fov_size': config.fov_size,
                    'mean_radius_px': config.get_mean_radius(n_neurons),
                }
                np.save(out_dir / (out_base + "_compact.npy"),
                        compact_data, allow_pickle=True)

            # Save dense version (CellReg-compatible N×H×W, can be large)
            if 'dense' in result:
                dense_data = {
                    'footprints': result['dense'],
                    'centroids_x': session_data['centroids_x'],
                    'centroids_y': session_data['centroids_y'],
                    'roi_ids': session_data['roi_ids'],
                    'fov_size': config.fov_size,
                    'mean_radius_px': config.get_mean_radius(n_neurons),
                }
                np.save(out_dir / (out_base + ".npy"),
                        dense_data, allow_pickle=True)

            file_count += 1

        if verbose:
            print(f"  Generated {file_count} footprint files"
                  f"{f', skipped {skip_count} existing' if skip_count else ''}"
                  f" → {out_dir}")

    print(f"\nDone.")


# ═══════════════════════════════════════════════════════════════════════════
# CLI entry point
# ═══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":

    # ╔═══════════════════════════════════════════════════════════════════╗
    # ║                     PATH CONFIGURATION                           ║
    # ╠═══════════════════════════════════════════════════════════════════╣

    BASE = Path(r"C:\Users\ariAccount\Desktop\Stars2CellsPaper")
    NEURON_COUNTS = [1000, 1000]
    BENCHMARK_DIRS = [
        BASE / "Stars2Cells_Benchmark_1000n_Tier_B",
        BASE / "Stars2Cells_Benchmark_1000n_Tier_C",
    ]

    N_ANIMALS = 8

    # ╠═══════════════════════════════════════════════════════════════════╣
    # ║               FOOTPRINT CONFIGURATION                            ║
    # ╠═══════════════════════════════════════════════════════════════════╣
    # ║  Scaling rationale (cited in module docstring):                   ║
    # ║    Mouse pyramidal soma ≈ 20 µm diameter                         ║
    # ║    (Bear et al., Neuroscience; Wikipedia "Pyramidal cell")        ║
    # ║    CNMF-E effective footprint ≈ 8–15 µm radius                   ║
    # ║    (Pnevmatikakis et al. 2016; Zhou et al. 2018)                 ║
    # ║    Inscopix CNMF-E: models neurons as ~spherical with            ║
    # ║    user-specified diameter (Inscopix blog, Feb 2024)             ║
    # ║                                                                   ║
    # ║  600×600 FOV → ~1.37× more area than 512², so same neuron        ║
    # ║  counts are sparser → slightly larger effective footprints.       ║
    # ╚═══════════════════════════════════════════════════════════════════╝

    config = FootprintConfig(
        fov_size=600,
        microns_per_pixel=1.0,
        radius_by_n={
            100:  12.0,   # ~24 µm diameter — sparse, full neuropil halo
            250:  10.0,   # ~20 µm — moderate density
            500:   8.0,   # ~16 µm — dense, CNMF shrinks footprints
            1000:  6.0,   # ~12 µm — very dense, near soma-only
        },
        eccentricity_range=(0.55, 1.0),  # wide variation for distinctiveness
        intensity_range=(0.5, 1.0), 
        radius_cv=0.20,                  # 20% CoV for size diversity
        normalize_footprints=True,
        # 'compact' saves ~1-5 MB per session (patches + bboxes).
        # 'both' saves both formats. Use reconstruct_dense_from_compact()
        # to get CellReg-compatible arrays from compact files on-the-fly.
        storage_mode='compact',
    )

    generate_all_footprints(
        benchmark_dirs=BENCHMARK_DIRS,
        n_neurons_list=NEURON_COUNTS,
        n_animals=N_ANIMALS,
        config=config,
        verbose=True,
    )